runtime: custom
env: flex

service: default

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  forwarded_ports:
    - 8080
    - 5000

includes:
  - env_variables.yaml