version: '3'
services:
  frontend:
    build: ./fe
    ports:
      - "5000:5000"
    environment:
      - VITE_API_ENDPOINT=http://backend:8080
      - VITE_CHROME_EXTENSION_ID=${CHROME_EXTENSION_ID}
    depends_on:
      - backend

  backend:
    build: ./be
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_URL=http://frontend:5000
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - CHROME_EXTENSION_ID=${CHROME_EXTENSION_ID}
    env_file:
      - be/.env